// <auto-generated />
using GestionFleur.ViewModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionFleur.Migrations
{
    [DbContext(typeof(GestionFleurContext))]
    [Migration("20250415184831_CreateDb2")]
    partial class CreateDb2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BouquetCommande", b =>
                {
                    b.Property<string>("BouquetsBouquetId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CommandesCommandeId")
                        .HasColumnType("int");

                    b.HasKey("BouquetsBouquetId", "CommandesCommandeId");

                    b.HasIndex("CommandesCommandeId");

                    b.ToTable("BouquetCommande");
                });

            modelBuilder.Entity("BouquetFleur", b =>
                {
                    b.Property<string>("BouquetsBouquetId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FleursFleurId")
                        .HasColumnType("int");

                    b.HasKey("BouquetsBouquetId", "FleursFleurId");

                    b.HasIndex("FleursFleurId");

                    b.ToTable("BouquetFleur");
                });

            modelBuilder.Entity("CommandeFleur", b =>
                {
                    b.Property<int>("CommandesCommandeId")
                        .HasColumnType("int");

                    b.Property<int>("FleursFleurId")
                        .HasColumnType("int");

                    b.HasKey("CommandesCommandeId", "FleursFleurId");

                    b.HasIndex("FleursFleurId");

                    b.ToTable("CommandeFleur");
                });

            modelBuilder.Entity("GestionFleur.Models.Bouquet", b =>
                {
                    b.Property<string>("BouquetId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MessageCarte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PrixUnitaire")
                        .HasColumnType("float");

                    b.HasKey("BouquetId");

                    b.ToTable("Bouquets");
                });

            modelBuilder.Entity("GestionFleur.Models.Commande", b =>
                {
                    b.Property<int>("CommandeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommandeId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<bool>("PaiementEffectue")
                        .HasColumnType("bit");

                    b.Property<double>("TotalTransaction")
                        .HasColumnType("float");

                    b.Property<int>("TypeDePaiement")
                        .HasColumnType("int");

                    b.Property<int>("VendeurId")
                        .HasColumnType("int");

                    b.HasKey("CommandeId");

                    b.HasIndex("ClientId");

                    b.HasIndex("VendeurId");

                    b.ToTable("Commandes");
                });

            modelBuilder.Entity("GestionFleur.Models.Fleur", b =>
                {
                    b.Property<int>("FleurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FleurId"));

                    b.Property<string>("couleur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("prixUnitaire")
                        .HasColumnType("float");

                    b.Property<int>("quantite")
                        .HasColumnType("int");

                    b.HasKey("FleurId");

                    b.ToTable("Fleurs");
                });

            modelBuilder.Entity("GestionFleur.Models.Utilisateur", b =>
                {
                    b.Property<int>("UtilisateurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UtilisateurId"));

                    b.Property<string>("Identifiant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UtilisateurId");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("BouquetCommande", b =>
                {
                    b.HasOne("GestionFleur.Models.Bouquet", null)
                        .WithMany()
                        .HasForeignKey("BouquetsBouquetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionFleur.Models.Commande", null)
                        .WithMany()
                        .HasForeignKey("CommandesCommandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BouquetFleur", b =>
                {
                    b.HasOne("GestionFleur.Models.Bouquet", null)
                        .WithMany()
                        .HasForeignKey("BouquetsBouquetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionFleur.Models.Fleur", null)
                        .WithMany()
                        .HasForeignKey("FleursFleurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommandeFleur", b =>
                {
                    b.HasOne("GestionFleur.Models.Commande", null)
                        .WithMany()
                        .HasForeignKey("CommandesCommandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionFleur.Models.Fleur", null)
                        .WithMany()
                        .HasForeignKey("FleursFleurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionFleur.Models.Commande", b =>
                {
                    b.HasOne("GestionFleur.Models.Utilisateur", "Client")
                        .WithMany("CommandesClient")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GestionFleur.Models.Utilisateur", "Vendeur")
                        .WithMany("CommandesASuperviser")
                        .HasForeignKey("VendeurId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Vendeur");
                });

            modelBuilder.Entity("GestionFleur.Models.Utilisateur", b =>
                {
                    b.Navigation("CommandesASuperviser");

                    b.Navigation("CommandesClient");
                });
#pragma warning restore 612, 618
        }
    }
}
